package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'GitHub'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("GitHub")) {
    expectBuildTypesOrder(RelativeId("GitHubBuildBuildIntellijBazel"), RelativeId("GitHubTestsIdeProbe"), RelativeId("GitHubTestsUnitTests"), RelativeId("GitHubResults"))
    buildTypesOrderIds = arrayListOf(RelativeId("GitHubBuildBuildIntellijBazel"), RelativeId("GitHubTestsIdeProbe"), RelativeId("GitHubTestsUnitTests"), RelativeId("GitHubresults"))
}
