package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'SpaceVcs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("SpaceVcs")) {
    val expected = GitVcsRoot({
        id("SpaceVcs")
        name = "intellij-bazel-space"
        url = "https://git.jetbrains.team/bazel/intellij-bazel.git"
        branch = "main"
        branchSpec = "+:refs/heads/*"
        authMethod = token {
            userName = "x-oauth-basic"
            tokenId = "tc_token_id:CID_ee3bac3e4aa54bdf48fee3b7b53cbc31:-1:8560ad34-1d4a-46f4-b15c-f3e2e7f3b874"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "x-oauth-basic"
            tokenId = "tc_token_id:CID_ee3bac3e4aa54bdf48fee3b7b53cbc31:-1:edabdbc7-0806-43a4-bf49-3fdb1bf56d95"
        }
    }

}
